[identity]
outputs = EXAMPLE-HDMI-1,EXAMPLE-DP-1
lid = closed
match_mode = contains

[layout]
primary = EXAMPLE-HDMI-1
order = EXAMPLE-HDMI-1,EXAMPLE-DP-1
output_1 = EXAMPLE-HDMI-1|0|0|2560x1440|60
output_2 = EXAMPLE-DP-1|2560|0|1920x1080|60
