#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command


# Verbosity and settings that you pretty much just always are going to want.
alias \
	batt="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
#	yt="youtube-dl --add-metadata -i" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
if [ "$(uname)" = "Darwin" ]; then
	alias \
		ls="ls -h" \
		sl="ls -h" \
		l.='ls -d .*' \
		ll='ls -hAlF' \
		ll.='ls -hAlFd .*' \
		pss='ps aux | grep -v grep | grep -i -e VSZ -e'
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
	alias \
		ls="ls -hN --color=auto --group-directories-first" \
		sl="ls -hN --color=auto --group-directories-first" \
		l.='ls -d .* --color=auto --group-directories-first' \
		ll='ls -hAlF --group-directories-first' \
		ll.='ls -hAlFd .* --group-directories-first' \
		diff="diff --color=auto" \
		pss='ps auxf | grep -v grep | grep -i -e VSZ -e'
fi

alias \
	grep="grep --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \
	which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde' \
	..='cd ..' \
	...='cd ..\..'

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	gua='git remote | xargs -L1 git push --all' \
	c='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME' \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	e="emacs" \
	p="pacman" \
	v="$EDITOR" \
	calcurse='calcurse -D ~/.config/calcurse' \
	x='sxiv -ft *' \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"
#	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"

# Customization
alias \
	lg="lazygit" \
	ra="ranger" \
	t="tldr" \
	emi='sudo emerge -pv' \
	emr='sudo emerge -Ca' \
	emu='sudo emerge-webrsync' \
	emw='sudo emerge -auDN @world' \
	emd='sudo emerge --depclean' \
