#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# This file's true location is in ~/.config/xprofile and a link exists to it in
# ~/.xprofile. If you do not use a DM, you may remove the link to it to have a
# cleaner home.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

eval "$(dbus-launch --sh-syntax --exit-with-session)"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

alias setproxy="export ALL_PROXY=http://127.0.0.1:10080"
#alias setproxy="export ALL_PROXY=socks5://127.0.0.1:1080"
alias unsetproxy="unset ALL_PROXY"
alias ip="curl -i http://ip.cn"

export GO111MODULE=on
export GOPROXY=https://goproxy.cn,direct

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
xset r rate 300 50 &	# Speed xrate up
fcitx &
if [ -f /usr/bin/synergy ]; then
	synergyc &
fi

autostart="mpd xcompmgr dunst unclutter pipewire"
for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

# mpd &			# music player daemon-you might prefer it as a service though
# xcompmgr &		# xcompmgr for transparency
# dunst &			# dunst for notifications
# unclutter &		# Remove mouse when idle

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
#pidof -s runit &&
#      ! pidof -s pulseaudio >/dev/null 2>&1 &&
#      setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

