# Shared xdisplay library loader. Callers must set XDISPLAY_LIB_DIR first.

[ -n "${XDISPLAY_LIB_DIR:-}" ] || {
    printf '%s\n' 'xdisplay: XDISPLAY_LIB_DIR is not set.' >&2
    return 1
}

FAST_WINDOW_CHECKS=10
FAST_QUERY_INTERVAL=2
STABLE_POLL_TICKS=1
SNAPSHOT_FAILURE_LIMIT=6

# Built-in defaults are intentionally kept next to the configuration schema.
CONFIG_TIMEOUT_SECONDS=2
CONFIG_KILL_AFTER_SECONDS=1
CONFIG_APPLY_FAILURE_LIMIT=3
CONFIG_APPLY_RETRY_TICKS=10
CONFIG_HARDWARE_PROBE_TICKS=120
CONFIG_PENDING_PROBE_TICKS=10
CONFIG_LOG_MAX_BYTES=1048576
CONFIG_LOG_PATH=${HOME}/.local/share/x11/xdisplay-adapter.log
CONFIG_EXTERNAL_POSITION=right
CONFIG_EXTERNAL_PRIMARY=first
CONFIG_MIRROR_ON_DUPLICATE=false
CONFIG_LAYOUT_FILE_PRESENT=0
CONFIG_PARSE_ERROR=0

PENDING_PROBE_TICKS=$CONFIG_PENDING_PROBE_TICKS
HARDWARE_PROBE_TICKS=$CONFIG_HARDWARE_PROBE_TICKS
APPLY_FAILURE_LIMIT=$CONFIG_APPLY_FAILURE_LIMIT
APPLY_RETRY_TICKS=$CONFIG_APPLY_RETRY_TICKS

XDISPLAY_USE_ADAPTER=${XDISPLAY_USE_ADAPTER:-0}
case "$XDISPLAY_USE_ADAPTER" in
    1) ;;
    *) XDISPLAY_USE_ADAPTER=0 ;;
esac
ADAPTER_PATH=${HOME}/.config/x11/xdisplay-device.local
ADAPTER_LOG=$CONFIG_LOG_PATH
ADAPTER_TIMEOUT=$CONFIG_TIMEOUT_SECONDS
ADAPTER_KILLAFTER=$CONFIG_KILL_AFTER_SECONDS
ADAPTER_LOG_MAX_BYTES=$CONFIG_LOG_MAX_BYTES
WATCH_LOCK_WAIT=8
MULTI_SCREEN_LAYOUT_READY=1

STATE_INTERNAL_ONLY=INTERNAL_ONLY
STATE_EXTERNAL_ONLY=EXTERNAL_ONLY
STATE_DUAL_EXTEND=DUAL_EXTEND
STATE_MULTI_EXTEND=MULTI_EXTEND
STATE_MULTI_EXTERNAL=MULTI_EXTERNAL
STATE_MIRROR=MIRROR
STATE_CUSTOM=CUSTOM
STATE_NONE=NONE
: "$STATE_MIRROR" "$STATE_CUSTOM"

ADAPTER_INTERNAL_OUTPUTS=
ADAPTER_INTERNAL_CACHE_KEY=
ADAPTER_INTERNAL_CACHE_VALUE=
ADAPTER_EXPECTED_OUTPUT=
ADAPTER_EXPECTED_VALID=0
ADAPTER_EXPECTED_PRESENT=0
ADAPTER_EXPECTED_CACHE_KEY=
ADAPTER_EXPECTED_CACHE_VALUE=
ADAPTER_EXPECTED_CACHE_VALID=0
ADAPTER_EXPECTED_MISSING_LOG_KEY=
ADAPTER_UNAVAILABLE_LOGGED=0
ADAPTER_RESTORE_ATTEMPTED=0
CURRENT_DISPLAY_STATE=$STATE_NONE
CURRENT_INTERNAL_OUTPUTS=
CURRENT_EXTERNAL_OUTPUTS=
CURRENT_DISPLAY_INTERNAL_COUNT=0
CURRENT_DISPLAY_EXTERNAL_COUNT=0
CURRENT_LAYOUT_FUNCTION=legacy
CUSTOM_LAYOUT_NAME=
CUSTOM_LAYOUT_PRIMARY=
CUSTOM_LAYOUT_ORDER=
CUSTOM_LAYOUT_POSITIONS=
CUSTOM_LAYOUT_LID=
CUSTOM_LAYOUT_MATCH_MODE=
CUSTOM_LAYOUT_MTIME=0

for xdisplay_library in \
    lib-utils.sh \
    lib-config-parse.sh \
    lib-config.sh \
    lib-runtime.sh \
    lib-log.sh \
    lib-adapter-run.sh \
    lib-snapshot.sh \
    lib-state.sh \
    lib-custom-parse.sh \
    lib-custom-validate.sh \
    lib-custom.sh \
    lib-output.sh \
    lib-adapter-query.sh \
    lib-topology.sh \
    lib-health.sh \
    lib-layout.sh \
    lib-custom-apply.sh \
    lib-layout-verify.sh \
    lib-adapter-restore.sh \
    lib-layout-configure.sh \
    lib-status.sh \
    lib-engine.sh \
    lib-select.sh; do
    [ -r "$XDISPLAY_LIB_DIR/$xdisplay_library" ] || {
        printf 'xdisplay: missing library: %s\n' \
            "$XDISPLAY_LIB_DIR/$xdisplay_library" >&2
        return 1
    }
    . "$XDISPLAY_LIB_DIR/$xdisplay_library" || return 1
done
unset xdisplay_library
