#!/bin/bash

wal_cache="${XDG_CACHE_HOME:-$HOME/.cache}/wal"
dunstconf="$wal_cache/dunstrc"

source "$wal_cache/colors.sh"

fix_sequences() {
        e=$'\e'
        sequences=$(cat)
        foreground_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]10[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
        background_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]11[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
        cursor_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]12[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"

	for term in /dev/pts/{0..9}*; do
		echo -e "\e]4;256;${cursor_color}\a\c" > "${term}" 2>/dev/null
		echo -e "\e]4;258;${background_color}\a\c" > "${term}" 2>/dev/null
		echo -e "\e]4;259;${foreground_color}\a\c" > "${term}" 2>/dev/null
	done
}

fix_sequences <"$wal_cache/sequences"

if command -v dunst >/dev/null 2>&1; then
	pkill dunst
	if command -v setsid >/dev/null 2>&1; then
		setsid -f dunst -conf "$dunstconf"
	else
		dunst -conf "$dunstconf" &
	fi
fi
